name: antrian
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  google_fonts: ^3.0.1
  google_sign_in: 5.3.3
  firebase_core: ^1.17.1
  firebase_auth: 3.3.19
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
    - assets/images/
    - assets/images/events/
    - assets/images/app/
    - assets/images/app/weathers/
  uses-material-design: true

